package to.crp.android.onlykeyu2f;

/**
 * Class representing events generated by an {@link OnlyKey}.
 */
class OKEvent {

    enum OKEType {
        ERROR, SET_INITIALIZED, SET_LOCKED, SET_TIME, MSG, DONE, U2F_RESPONSE
    }

    private final OnlyKey key;
    private final OKEType type;
    private final boolean boolVal;
    private final String stringVal;
    private final Exception e;

    /**
     * Create an event.
     *
     * @param key  The OnlyKey generating the event.
     * @param type The event type.
     * @param e    The exception value.
     */
    OKEvent(final OnlyKey key, final OKEType type, final Exception e) {
        this(key, type, false, e, "");
    }

    /**
     * Create an event.
     *
     * @param key     The OnlyKey generating the event.
     * @param type    The event type.
     * @param boolVal The boolean value.
     */
    OKEvent(final OnlyKey key, final OKEType type, final boolean boolVal) {
        this(key, type, boolVal, new Exception(), "");
    }

    /**
     * Create an event.
     *
     * @param key       The OnlyKey generating the event.
     * @param type      The event type.
     * @param stringVal THe string value.
     */
    OKEvent(final OnlyKey key, final OKEType type, final String stringVal) {
        this(key, type, false, new Exception(), stringVal);
    }

    /**
     * Create an event.
     *
     * @param type      The event type.
     * @param boolVal   The boolean value.
     * @param e         The exception value.
     * @param stringVal The string value.
     */
    private OKEvent(final OnlyKey key, final OKEType type, final boolean boolVal, final Exception
            e, final String stringVal) {
        this.key = key;
        this.type = type;
        this.boolVal = boolVal;
        this.e = e;
        this.stringVal = stringVal;
    }

    /**
     * @return The boolean value.
     */
    boolean getBoolVal() {
        return boolVal;
    }

    /**
     * @return The string value.
     */
    String getStringVal() {
        return stringVal;
    }

    /**
     * @return The event type.
     */
    OKEType getType() {
        return type;
    }

    /**
     * @return The exception value.
     */
    Exception getException() {
        return e;
    }
}
